[nccsurl]
catalog_url = "https://urbaninstitute.github.io/nccs/catalogs/catalog-efile-v2_1.html"
catalog_dict = "https://nonprofit-open-data-collective.github.io/irs990efile/data-dictionary/data-dictionary.html"
[dbconn]
connstr="DRIVER={ODBC Driver 18 for SQL Server};Server=DESKTOP-KR1CQDE\\SERVERA;Database=nccs990_test;UID=sa;PWD=sa;TrustServerCertificate=yes"
[output]
build="reload" # new - drop all tables, reload check and create for new
raw_data ="raw_files"
raw_parq ="parquets"
[logging]
debug = 0
